/**
 * 액션 타입
 */
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const CLEAR_POST = 'CLEAR_POST';

// 모바일 메뉴
export const MENU_TOGGLE = 'MENU_TOGGLE';

// admin upload
export const PRODUCT_POST_SUCCESS = 'PRODUCT_POST_SUCCESS';
export const PRODUCT_POST_FAILURE = 'PRODUCT_POST_FAILURE';
export const PRODUCT_POST_IMAGE_SUCCESS = 'PRODUCT_POST_IMAGE_SUCCESS';
export const PRODUCT_POST_IMAGE_FAILURE = 'PRODUCT_POST_IMAGE_FAILURE';
export const PRODUCT_IMAGE_REMOVE = 'PRODUCT_IMAGE_REMOVE';
export const EDIT_PRODUCT_IMAGE_REMOVE = 'EDIT_PRODUCT_IMAGE_REMOVE';
export const EDIT_PRODUCT_POST_IMAGE_SUCCESS =
  'EDIT_PRODUCT_POST_IMAGE_SUCCESS';
export const EDIT_PRODUCT_POST_IMAGE_FAILURE =
  'EDIT_PRODUCT_POST_IMAGE_FAILURE';

// admin product
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const GET_ALL_PRODUCT_FAILURE = 'GET_ALL_PRODUCT_FAILURE';
export const PRODUCT_READ = 'PRODUCT_READ';
export const PRODUCT_READ_FAILURE = 'PRODUCT_READ_FAILURE';

// user cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_CART_ITEMS = 'GET_CART_ITEMS';
export const CART_FAILURE = 'CART_FAILURE';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';

// reviews
export const REVIEW_POST_SUCCESS = 'REVIEW_POST_SUCCESS';
export const REVIEW_POST_FAILURE = 'REVIEW_POST_FAILURE';
export const CLEAR_REVIEW = 'CLEAR_REVIEW';
export const GET_ALL_REVIEWS = 'GET_ALL_REVIEWS';
export const GET_ALL_REVIEWS_FAILURE = 'GET_ALL_REVIEWS_FAILURE';
export const REVIEW_READ = 'REVIEW_READ';
export const REVIEW_READ_FAILURE = 'REVIEW_READ_FAILURE';
