/**
 * 액션 타입
 */
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const CLEAR_POST = 'CLEAR_POST';

// 모바일 메뉴
export const MENU_TOGGLE = 'MENU_TOGGLE';

// admin upload
export const PRODUCT_POST_SUCCESS = 'PRODUCT_POST_SUCCESS';
export const PRODUCT_POST_FAILURE = 'PRODUCT_POST_FAILURE';
export const PRODUCT_POST_IMAGE_SUCCESS = 'PRODUCT_POST_IMAGE_SUCCESS';
export const PRODUCT_POST_IMAGE_FAILURE = 'PRODUCT_POST_IMAGE_FAILURE';
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';
